name = "FuseRegistry"
uuid = "2efecdb0-7a2e-456a-9eaf-01cb596ca5a1"
repo = "https://github.com/ProjectTorreyPines/FuseRegistry.jl.git"
description = "Registry of Julia packages related to FUSE.jl or IMASDD.jl"

[packages]
06b86afa-9f21-11ec-2ef8-e51b8960cfc5 = { name = "IMASDD", path = "I/IMASDD" }
081d0416-0f87-42c0-8034-5895805e76d8 = { name = "NEO", path = "N/NEO" }
09becab6-0636-4c23-a92a-2b3723265c31 = { name = "SOLPS2IMAS", path = "S/SOLPS2IMAS" }
12ecd31c-256b-4db5-a799-cd5afeb0bd7d = { name = "TJLF", path = "T/TJLF" }
13ead8c1-b7d1-41bb-a6d0-5b8b65ed587a = { name = "IMAS", path = "I/IMAS" }
2da5b0d0-c5e5-4f14-9caf-62d0020df410 = { name = "BoundaryPlasmaModels", path = "B/BoundaryPlasmaModels" }
32ab26d3-25d6-405d-a295-367385e16093 = { name = "SimulationParameters", path = "S/SimulationParameters" }
40781a8e-f1bb-11ec-24ef-0f6bc40c1567 = { name = "CHEASE", path = "C/CHEASE" }
4c86da02-02c8-4634-8460-96566129f8e0 = { name = "FusionMaterials", path = "F/FusionMaterials" }
558c7b13-fd9f-4806-b461-592296cfa9d0 = { name = "TGLFNN", path = "T/TGLFNN" }
68b8b4ac-b179-4f07-8ae9-c1f1360acbca = { name = "ThermalSystemModels", path = "T/ThermalSystemModels" }
6ce10167-d368-4c0e-af34-9787cdd175e5 = { name = "FiniteElementHermite", path = "F/FiniteElementHermite" }
7204ce3a-f536-43d2-be4a-fbed74e90d86 = { name = "CoordinateConventions", path = "C/CoordinateConventions" }
804828d9-b4e9-4eca-b847-748d6c7bafa9 = { name = "MeshTools", path = "M/MeshTools" }
8bcbec86-48c7-11ec-16a6-c1bc83299373 = { name = "QED", path = "Q/QED" }
8efa4e5a-7b9a-4eec-876e-01d13d5b5d75 = { name = "MXHEquilibrium", path = "M/MXHEquilibrium" }
8fb689aa-71ff-4044-8071-0cffc910b57d = { name = "Fortran90Namelists", path = "F/Fortran90Namelists" }
95ff35a0-be81-11e9-2ca3-5b4e338e8476 = { name = "XSteam", path = "X/XSteam" }
9d9223b5-c5da-4bf4-abee-2a8bb6775a49 = { name = "VacuumFields", path = "V/VacuumFields" }
a60c9cbd-e72f-4185-96b6-b8fc312c4d37 = { name = "TEQUILA", path = "T/TEQUILA" }
a9424c20-d414-11ec-167b-9106c24d956c = { name = "NNeutronics", path = "N/NNeutronics" }
b7b5e640-9b39-4803-84eb-376048795def = { name = "GGDUtils", path = "G/GGDUtils" }
c6e34158-aa22-49e4-bb12-15cbcb518ce6 = { name = "SynthDiag", path = "S/SynthDiag" }
c82744c2-dc08-461a-8c37-87ab04d0f9b8 = { name = "MillerExtendedHarmonic", path = "M/MillerExtendedHarmonic" }
c8e4ee58-0bec-4a6a-b552-9dd24d6374ac = { name = "FuseUtils", path = "F/FuseUtils" }
c9827a86-0873-413c-b74b-de8fe857399a = { name = "GenerateDD", path = "G/GenerateDD" }
d40c7a0e-b328-4954-9d8e-c203ade7593f = { name = "XSteamTP", path = "X/XSteamTP" }
d8db6f1b-e564-4c04-bba3-ef399f78c070 = { name = "SD4SOLPS", path = "S/SD4SOLPS" }
e356478e-5a30-45f6-9775-70cc66e4fbd4 = { name = "FXP", path = "F/FXP" }
e64856f0-3bb8-4376-b4b7-c03396503991 = { name = "EPEDNN", path = "E/EPEDNN" }
e64856f0-3bb8-4376-b4b7-c03396503992 = { name = "FUSE", path = "F/FUSE" }
f4a0d185-1024-41e7-8ef7-3196bb2f6549 = { name = "ADAS", path = "A/ADAS" }
