name = "FuseRegistry"
uuid = "2efecdb0-7a2e-456a-9eaf-01cb596ca5a1"
repo = "https://github.com/ProjectTorreyPines/FuseRegistry.jl.git"
description = "Registry of Julia packages related to FUSE.jl or IMASdd.jl"

[packages]
001e48cb-5a1e-4e3c-a5d4-cdc3aa14f3de = { name = "BalanceOfPlantSurrogate", path = "B/BalanceOfPlantSurrogate" }
081d0416-0f87-42c0-8034-5895805e76d8 = { name = "NEO", path = "N/NEO" }
12ecd31c-256b-4db5-a799-cd5afeb0bd7d = { name = "TJLF", path = "T/TJLF" }
13ead8c1-b7d1-41bb-a6d0-5b8b65ed587a = { name = "IMAS", path = "I/IMAS" }
2da5b0d0-c5e5-4f14-9caf-62d0020df410 = { name = "BoundaryPlasmaModels", path = "B/BoundaryPlasmaModels" }
32ab26d3-25d6-405d-a295-367385e16093 = { name = "SimulationParameters", path = "S/SimulationParameters" }
40781a8e-f1bb-11ec-24ef-0f6bc40c1567 = { name = "CHEASE", path = "C/CHEASE" }
43dcb517-7681-482a-b959-351932bd0b36 = { name = "FuseExchangeProtocol", path = "F/FuseExchangeProtocol" }
46fde914-2a1c-4f77-9b2f-1c21d94fe0f1 = { name = "CoordinatesSystems", path = "C/CoordinatesSystems" }
4c86da02-02c8-4634-8460-96566129f8e0 = { name = "FusionMaterials", path = "F/FusionMaterials" }
50b852fb-755b-4f1c-b4e6-649ec8fe8474 = { name = "FusionSpecies", path = "F/FusionSpecies" }
558c7b13-fd9f-4806-b461-592296cfa9d0 = { name = "TGLFNN", path = "T/TGLFNN" }
68b8b4ac-b179-4f07-8ae9-c1f1360acbca = { name = "ThermalSystemModels", path = "T/ThermalSystemModels" }
6ce10167-d368-4c0e-af34-9787cdd175e5 = { name = "FiniteElementHermite", path = "F/FiniteElementHermite" }
7204ce3a-f536-43d2-be4a-fbed74e90d86 = { name = "CoordinateConventions", path = "C/CoordinateConventions" }
804828d9-b4e9-4eca-b847-748d6c7bafa9 = { name = "MeshTools", path = "M/MeshTools" }
8217f67a-9bf0-495c-a6dc-30c3fb73287a = { name = "PAM", path = "P/PAM" }
8bcbec86-48c7-11ec-16a6-c1bc83299373 = { name = "QED", path = "Q/QED" }
8efa4e5a-7b9a-4eec-876e-01d13d5b5d75 = { name = "MXHEquilibrium", path = "M/MXHEquilibrium" }
8fb689aa-71ff-4044-8071-0cffc910b57d = { name = "Fortran90Namelists", path = "F/Fortran90Namelists" }
95ff35a0-be81-11e9-2ca3-5b4e338e8476 = { name = "XSteam", path = "X/XSteam" }
98960a00-302f-469e-9595-275b70d10766 = { name = "RABBIT", path = "R/RABBIT" }
9d9223b5-c5da-4bf4-abee-2a8bb6775a49 = { name = "VacuumFields", path = "V/VacuumFields" }
a60c9cbd-e72f-4185-96b6-b8fc312c4d37 = { name = "TEQUILA", path = "T/TEQUILA" }
a9424c20-d414-11ec-167b-9106c24d956c = { name = "NNeutronics", path = "N/NNeutronics" }
b8e4ee59-9bed-3a6a-a553-8dd24d6374ad = { name = "IMASutils", path = "I/IMASutils" }
c0158764-c6e1-428b-a545-31826f389bc8 = { name = "TroyonBetaNN", path = "T/TroyonBetaNN" }
c5a45a97-b3f9-491c-b9a7-aa88c3bc0067 = { name = "IMASdd", path = "I/IMASdd" }
c82744c2-dc08-461a-8c37-87ab04d0f9b8 = { name = "MillerExtendedHarmonic", path = "M/MillerExtendedHarmonic" }
c8e4ee58-0bec-4a6a-b552-9dd24d6374ac = { name = "FuseUtils", path = "F/FuseUtils" }
c9827a86-0873-413c-b74b-de8fe857399a = { name = "GenerateDD", path = "G/GenerateDD" }
cda752c5-6b03-55a3-9e33-132a441b0c17 = { name = "EFIT", path = "E/EFIT" }
d079e620-cbd9-4d56-ad78-ffea50be2e33 = { name = "TJLFEP", path = "T/TJLFEP" }
d40c7a0e-b328-4954-9d8e-c203ade7593f = { name = "XSteamTP", path = "X/XSteamTP" }
d8db6f1b-e564-4c04-bba3-ef399f78c070 = { name = "SD4SOLPS", path = "S/SD4SOLPS" }
e356478e-5a30-45f6-9775-70cc66e4fbd4 = { name = "FXP", path = "F/FXP" }
e64856f0-3bb8-4376-b4b7-c03396503991 = { name = "EPEDNN", path = "E/EPEDNN" }
e64856f0-3bb8-4376-b4b7-c03396503992 = { name = "FUSE", path = "F/FUSE" }
f2db6eb9-2c54-4c18-912b-ce467796777a = { name = "FRESCO", path = "F/FRESCO" }
f4a0d185-1024-41e7-8ef7-3196bb2f6549 = { name = "ADAS", path = "A/ADAS" }
